
package br.com.cmdev.ws.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.10
 * 2021-08-10T05:54:47.792-03:00
 * Generated source version: 3.3.10
 */

@WebFault(name = "AutenticacaoFault", targetNamespace = "http://service.ws.cmdev.com.br/")
public class AutenticacaoException extends Exception {

    private java.lang.String faultInfo;

    public AutenticacaoException() {
        super();
    }

    public AutenticacaoException(String message) {
        super(message);
    }

    public AutenticacaoException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AutenticacaoException(String message, java.lang.String autenticacaoFault) {
        super(message);
        this.faultInfo = autenticacaoFault;
    }

    public AutenticacaoException(String message, java.lang.String autenticacaoFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = autenticacaoFault;
    }

    public java.lang.String getFaultInfo() {
        return this.faultInfo;
    }
}
