package br.com.cmdev.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.10
 * 2021-08-10T05:54:47.834-03:00
 * Generated source version: 3.3.10
 *
 */
@WebService(targetNamespace = "http://service.ws.cmdev.com.br/", name = "EstoqueWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EstoqueWS {

    @WebMethod(operationName = "ListarTodosItens")
    @Action(input = "http://service.ws.cmdev.com.br/EstoqueWS/ListarTodosItensRequest", output = "http://service.ws.cmdev.com.br/EstoqueWS/ListarTodosItensResponse")
    @RequestWrapper(localName = "ListarTodosItens", targetNamespace = "http://service.ws.cmdev.com.br/", className = "br.com.cmdev.ws.service.ListarTodosItens")
    @ResponseWrapper(localName = "todosItens", targetNamespace = "http://service.ws.cmdev.com.br/", className = "br.com.cmdev.ws.service.TodosItens")
    @WebResult(name = "itens", targetNamespace = "")
    public java.util.List<br.com.cmdev.ws.service.Item> listarTodosItens()
;

    @WebMethod(operationName = "ListarItensPorFiltro")
    @Action(input = "http://service.ws.cmdev.com.br/EstoqueWS/ListarItensPorFiltroRequest", output = "http://service.ws.cmdev.com.br/EstoqueWS/ListarItensPorFiltroResponse")
    @RequestWrapper(localName = "ListarItensPorFiltro", targetNamespace = "http://service.ws.cmdev.com.br/", className = "br.com.cmdev.ws.service.ListarItensPorFiltro")
    @ResponseWrapper(localName = "itens", targetNamespace = "http://service.ws.cmdev.com.br/", className = "br.com.cmdev.ws.service.Itens")
    @WebResult(name = "itens", targetNamespace = "")
    public br.com.cmdev.ws.service.ListaItens listarItensPorFiltro(

        @WebParam(name = "filtros", targetNamespace = "")
        br.com.cmdev.ws.service.Filtros filtros
    );

    @WebMethod(operationName = "CadastrarItem")
    @Action(input = "http://service.ws.cmdev.com.br/EstoqueWS/CadastrarItemRequest", output = "http://service.ws.cmdev.com.br/EstoqueWS/CadastrarItemResponse", fault = {@FaultAction(className = AutenticacaoException.class, value = "http://service.ws.cmdev.com.br/EstoqueWS/CadastrarItem/Fault/AutenticacaoException")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CadastrarItemResponse", targetNamespace = "http://service.ws.cmdev.com.br/", partName = "result")
    public CadastrarItemResponse cadastrarItem(

        @WebParam(partName = "parameters", name = "CadastrarItem", targetNamespace = "http://service.ws.cmdev.com.br/")
        CadastrarItem parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://service.ws.cmdev.com.br/", header = true)
        TokenUsuario token
    ) throws AutenticacaoException;
}
